# Site settings
title: Blog | Antonio Moon´s
motto: un blog sobre mi, juegos, desarrollo y anime
author: Antonio Mateo
email: antoniomt.moon@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://moonantonio.github.io/" # the base hostname & protocol for your site
github_username:  MoonAntonio
description: un blog sobre mi, juegos, desarrollo y anime

# Build settings
markdown: kramdown

include: [".well-known"]

plugins:
  - jekyll-sitemap